name: authapp
description: "This is the flutter application build with bloc & clean architecture to implement the biometric auth - Assignment."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  fpdart: ^1.1.1
  flutter_bloc: ^9.1.1
  supabase_flutter: ^2.9.1
  get_it: ^8.0.3
  local_auth: ^2.3.0
  flutter_secure_storage: ^9.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  fonts:
    - family: JetBrainsMonoNerd
      fonts:
        - asset: assets/fonts/JetBrainsMonoNerd/JetBrainsMonoNerdFont-Regular.ttf
          style: normal
        - asset: assets/fonts/JetBrainsMonoNerd/JetBrainsMonoNerdFont-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/JetBrainsMonoNerd/JetBrainsMonoNerdFont-Bold.ttf
          weight: 600
        - asset: assets/fonts/JetBrainsMonoNerd/JetBrainsMonoNerdFont-Light.ttf
